convention_name: CMIP_GFDL
var_names:
  lat_coord: lat
  lon_coord: lon
  lev_coord: plev19
  time_coord: time
  lat_var: lat
  lon_var: lon
  time_var: time
  lev_var: plev19

  ua_var: ua
  va_var: va
  zg_var: zg
  pr_var: pr
  prc_var: prc
  prls_var: PRECL
  rlut_var: rlut
  FSNTOA_var: FSNTOA
  tas_var: ta
  ts_var: TS
  LANDFRAC_var: LANDFRAC
  tauu_var: TAUX
  CLDTOT_var: CLDTOT
  ICEFRAC_var: ICEFRAC
  ps_var: ps
  psl_var: PSL
  qa_var: hus   #Specific humidity
  u_var: ua
  v_var: va
  u200_var: ua
  v200_var: va
  u250_var: ua
  v250_var: va
  u850_var: ua
  v850_var: va
  omega500_var: wap
  wap_var: wap
  z250_var: zg
  pr_conversion_factor: 1 # units in CAM (m/s), convert to kg/m2/s (mm/s)
  prc_conversion_factor: 1 # units in CAM (m/s), convert to kg/m2/s (mm/s)
  prls_conversion_factor: 1 # units in CAM (m/s), convert to kg/m2/s (mm/s)

  # ------------------------------------------------------------------------
  # Variables for Convective Transition Diagnostics module:
  ta_var: ta # 3D temperature, units = K   
  prw_var: prw # Column Water Vapor (precipitable water vapor), units = mm (or kg/m^2)
  tave_var: tave # Mass-Weighted Column Average Tropospheric Temperature, units = K
  qsat_int_var: qsat_int # Vertically-Integrated Saturation Specific Humidity, units = mm (or kg/m^2)
  # End - Variables for Convective Transition Diagnostics package
  # ------------------------------------------------------------------------
  # ------------------------------------------------------------------------------------------------------------------
  # Variables name setting MJO Teleconnection Diagnostics module:(for USE of SpCCSM4 model)
  # ------------------------------------------------------------------------------------------------------------------
  #  pr_var: prec" # Total precipitation (mm/day)   
  #  rlut_var: olr" # Outgoing longwave radiation (w/m2)
  #  u850_var: u850" #Zonal wind at 850-hPa level(m/s)
  #  u250_var: u250" # Zonal wind at 250-hPa level(m/s)
  #  z250_var: z3250" #Geopotential height at 250-hPa level(m)
  pr_conversion_mm_day: 86400 # units in CAM (m/s), convert to (mm/day) required for plotting

  # ------------------------------------------------------------------------
  # Variables for mjo_diag (MJO propogation)

  ###   radiative fluxes 
  rsus_var: rsus
  rsds_var: rsds
  rsdt_var: rsdt
  rsut_var: rsut
  rlus_var: rlus
  rlds_var: rlds
  rlut_var: rlut
  hfss_var: hfss
  hfls_var: hfls

  # Variables for SM_ET_coupling module:
  mrsos_var: mrsos 
  evspsbl_var: evspsbl 