convention_name: CESM
var_names:
  hyam_var: hyam
  hybm_var: hybm
  lat_coord: lat
  lon_coord: lon
  lev_coord: lev
  time_coord: time
  lat_var: lat
  lon_var: lon
  time_var: time

  ua_var: U
  zg_var: Z3
  pr_var: PRECT
  prc_var: PRECC
  prls_var: PRECL
  rlut_var: FLUT
  FSNTOA_var: FSNTOA
  tas_var: TREFHT
  ts_var: TS
  LANDFRAC_var: LANDFRAC
  tauu_var: TAUX
  CLDTOT_var: CLDTOT
  ICEFRAC_var: ICEFRAC
  ps_var: PS
  psl_var: PSL
  qa_var: Q #Specific humidity
  u_var: U
  v_var: V
  u200_var: U200
  v200_var: V200
  u250_var: U250
  v250_var: V250
  u850_var: U850
  v850_var: V850
  omega500_var: OMEGA500
  z250_var: Z250
  pr_conversion_factor: 1000 # units in CAM (m/s), convert to kg/m2/s (mm/s)
  prc_conversion_factor: 1000 # units in CAM (m/s), convert to kg/m2/s (mm/s)
  prls_conversion_factor: 1000 # units in CAM (m/s), convert to kg/m2/s (mm/s)

  # ------------------------------------------------------------------------
  # Variables for Convective Transition Diagnostics module:
  ta_var: T # 3D temperature, units = K   
  prw_var: prw # Column Water Vapor (precipitable water vapor), units = mm (or kg/m^2)
  tave_var: tave # Mass-Weighted Column Average Tropospheric Temperature, units = K
  qsat_int_var: qsat_int # Vertically-Integrated Saturation Specific Humidity, units = mm (or kg/m^2)


  # ------------------------------------------------------------------------------------------------------------------
  # Variables name setting MJO Teleconnection Diagnostics module:(for USE of SpCCSM4 model)
  #pr_var: prec # Total precipitation (mm/day)   
  #rlut_var: olr # Outgoing longwave radiation (w/m2)
  #u850_var: u850 #Zonal wind at 850-hPa level(m/s)
  #u250_var: u250 # Zonal wind at 250-hPa level(m/s)
  #z250_var: z3250 #Geopotential height at 250-hPa level(m)
  pr_conversion_mm_day: 86400000 # units in CAM (m/s), convert to (mm/day) required for plotting


  # ------------------------------------------------------------------------
  # Variables for mjo_diag (MJO propogation)
